### ISSUE TITLE
Implementing coref (for english)

### ISSUE THREAD

**Issue by telion2** [gerardobort/node-corenlp#33]
Hi guys. I wanted to inquire about the status and plan on the implementation of coref. Apparently it is not implemented yet if looked up in the API Documentation. Since I'm building a tool where this would be a nice feature I would like to know if this will be implemented any time soon. 

If this isnt the case: Can you sketch a way to implement it? I realized that the pipeline would even throw an error if I set "dcoref" in the corenlp.Properties: 
`(node:3320) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'toString' of undefined
`
Code:
 `
 nlpStatus.connector = new corenlp.ConnectorServer({dsn: nlpStatus.host});
    nlpStatus.props = new corenlp.Properties({
        annotators: 'tokenize,ssplit,pos,lemma,ner,parse, dcoref'});

    nlpStatus.pipeline = new corenlp.Pipeline(nlpStatus.props, language , nlpStatus.connector);`

So my request is that the pipeline just generally can use this annotator so I can extract the coreference information out of it. Thank you for your time and replys.

**Comment by gerardobort** [comment]
Hi @telion2,

You're right, it's not implemented yet.  I have this and SentimentAnnotator as the top priorities for next updates - want to get full support for annotators. I'll try to work on this within this weekend (at least come up with the tests, in order to have a structure).  If you have any proposal, keeping in mind the code styling and model of other annotators, I'd be glad to merge your contribution - please, expect some back and forth until it's good to go.

Thanks!
